/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscribeRouteImport } from './routes/inscribe'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as VerseRouteImport } from './routes/verse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscribeRoute = InscribeRouteImport.update({
  id: '/inscribe',
  path: '/inscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseRoute = VerseRouteImport.update({
  id: '/verse',
  path: '/verse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscribe': typeof InscribeRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/verse': typeof VerseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscribe': typeof InscribeRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/verse': typeof VerseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inscribe': typeof InscribeRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/verse': typeof VerseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inscribe' | '/practice' | '/progress' | '/verse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inscribe' | '/practice' | '/progress' | '/verse'
  id: '__root__' | '/' | '/inscribe' | '/practice' | '/progress' | '/verse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InscribeRoute: typeof InscribeRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  VerseRoute: typeof VerseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscribe': {
      id: '/inscribe'
      path: '/inscribe'
      fullPath: '/inscribe'
      preLoaderRoute: typeof InscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse': {
      id: '/verse'
      path: '/verse'
      fullPath: '/verse'
      preLoaderRoute: typeof VerseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InscribeRoute: InscribeRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  VerseRoute: VerseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
